FROM rabbitmq:3.11.19-management-alpine as build

FROM rust:latest

WORKDIR /usr/src/app

COPY . .
COPY --from=build /usr/local/bin/rabbitmqadmin /usr/bin/rabbitmqadmin

RUN cargo test

CMD ["cargo", "test", "", "--", "--ignored", " --nocapture"]
