version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.11.19-management-alpine
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # RabbitMQ management console port
    networks:
      - test_network

  init_rabbitmq:
    image: rabbitmq:3.11.19-management-alpine
    networks:
      - test_network

  test_runner:
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
      dockerfile: Dockerfile.testrunner
    depends_on:
      - init_rabbitmq
    environment:
      - RABBIT_SERVER=rabbitmq
    networks:
      - test_network

networks:
  test_network:
    driver: bridge