[package]
name = "easyamqp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
tokio = { version = "1.29.1", features = ["full"] }
amqprs = "1.4.0"
async-trait = "0.1.73"

